### ISSUE TITLE
100% Usage

### ISSUE THREAD

**Issue by Quintisimo** [callisto2410/stylus-language#1]
When I install the package my CPU and RAM usage jumps to 100% usage

**Comment by callisto2410** [comment]
Try to reinstall the plugin, restart Atom.

What's your CPU, how much RAM and what OS.

When parsing the code, not a long load is normal, try to open a small stylus file

**Comment by Quintisimo** [comment]
I have an i5 processor, 8gb ram, windows 10. I was using a file with about 80 lines of code. It would just freeze atom and never unfreeze. I tried the other package, but yours has the best highlighting support :)

**Comment by callisto2410** [comment]
Ok, could you give me a list of installed plugins and the Atom version so I can reproduce the bug?

To find out the list of plugins, run the command:
```bash
apm list --installed
```

**Comment by Quintisimo** [comment]
Here is my list  of installed packages
````````````````````````````````````````````````````````````````````````````````````````````````
Community Packages (19) C:\Users\quint\.atom\packages
├── atom-pug@0.2.0
├── autoprefixer@3.7.1
├── busy-signal@1.4.3
├── file-icons@2.1.12
├── intentions@1.1.5
├── linter@2.2.0
├── linter-coffeescript@1.0.0
├── linter-htmlhint@1.3.3
├── linter-jshint@3.1.5
├── linter-php@1.5.0
├── linter-pug-lint@0.2.0
├── linter-stylelint@4.0.2
├── linter-stylint-h@0.0.15
├── linter-ui-default@1.6.10
├── open-in-browser@0.5.2
├── php-server@0.7.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.6.0
└── stylus-language@2.4.6

**Comment by callisto2410** [comment]
So, at Atom 1.20.1 the problem could not be reproduced.

Try to disable plug-ins one at a time, start with **pigments** and **linter-stylint-h**, do not forget to restart Atom, it's possible to detect the conflicting plugin.

If this does not work, try reinstalling Atom, installing plug-ins one by one, do not forget to back up the folder C:\Users\quint\.atom

**Comment by Quintisimo** [comment]
I tired everything you said but it still persists.

**Comment by callisto2410** [comment]
I can not reproduce the problem, so while I can not help you, try the plugins [Stylus](https://atom.io/packages/stylus) or [language-stylus](https://atom.io/packages/language-stylus), when using them there are no performance problems?

Stay tuned for updates, and I'll do some optimization.
